version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: src/
        target: /var/www/html
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local